# This file was generated by GoReleaser. DO NOT EDIT.
cask "movidesk-cli" do
  version "1.3.0"

  on_macos do
    on_intel do
      sha256 "70c3f2a64aadd0781273bccd85868009275e6bf618ea24ba8f5a57583596c847"
      url "https://github.com/jonasandre/movidesk-cli/releases/download/v#{version}/movidesk-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0dacff5019cabaa07bc04aef012de4818c05f71952b7ee72ef6605b6cf78012d"
      url "https://github.com/jonasandre/movidesk-cli/releases/download/v#{version}/movidesk-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5190d4867559aba8c8bd7c9c8135fca67ac967c7908c18a781cd887fd8b30168"
      url "https://github.com/jonasandre/movidesk-cli/releases/download/v#{version}/movidesk-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ce8b68e58d629277aa48127fe4e4ecc48324c27aa17bd45d9d9f34755254615a"
      url "https://github.com/jonasandre/movidesk-cli/releases/download/v#{version}/movidesk-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "movidesk-cli"
  desc "CLI for the Movidesk REST API"
  homepage "https://github.com/jonasandre/movidesk-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "movidesk-cli"
  bash_completion "completions/movidesk-cli.bash"
  fish_completion "completions/movidesk-cli.fish"
  zsh_completion "completions/movidesk-cli.zsh"

  # No zap stanza required

end
