# This file was generated by GoReleaser. DO NOT EDIT.
cask "movidesk-cli" do
  version "1.4.0"

  on_macos do
    on_intel do
      sha256 "ca88df575557c57b5dc716ee373c425ed60e5f91bad8897188b2aef387bba66c"
      url "https://github.com/jonasandre/movidesk-cli/releases/download/v#{version}/movidesk-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f3b5dfff9a8d880d236f25f6ef115730769a70d74e1b47140c4b80a67057a1d6"
      url "https://github.com/jonasandre/movidesk-cli/releases/download/v#{version}/movidesk-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bb528555a9f8c9daccec84e51fc7aa263850ac869df92532d6f87553a49d3b54"
      url "https://github.com/jonasandre/movidesk-cli/releases/download/v#{version}/movidesk-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d611ec32081167236c9f74cc4ba66de1b1be47a2160dfab09bd3bd369be928aa"
      url "https://github.com/jonasandre/movidesk-cli/releases/download/v#{version}/movidesk-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "movidesk-cli"
  desc "CLI for the Movidesk REST API"
  homepage "https://github.com/jonasandre/movidesk-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "movidesk-cli"
  bash_completion "completions/movidesk-cli.bash"
  fish_completion "completions/movidesk-cli.fish"
  zsh_completion "completions/movidesk-cli.zsh"

  # No zap stanza required

end
