# This file was generated by GoReleaser. DO NOT EDIT.
cask "movidesk-cli" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "91641878f451ec87fba4584a37aa12513b17f5c5a472254e865741c521e0003b"
      url "https://github.com/jonasandre/movidesk-cli/releases/download/v#{version}/movidesk-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bbdf0f9fbf9f483fcddac65e36211856f80dfc562db85e2f2096a087a44abf09"
      url "https://github.com/jonasandre/movidesk-cli/releases/download/v#{version}/movidesk-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3814a47b975370c2eee2a088733048bb8368bec8563e5584510fd42512fc0118"
      url "https://github.com/jonasandre/movidesk-cli/releases/download/v#{version}/movidesk-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d6cb253227bb990f58ae2b446ba6459638c4287ae839aa42d68346d66dbb12a6"
      url "https://github.com/jonasandre/movidesk-cli/releases/download/v#{version}/movidesk-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "movidesk-cli"
  desc "CLI for the Movidesk REST API"
  homepage "https://github.com/jonasandre/movidesk-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "movidesk-cli"
  bash_completion "completions/movidesk-cli.bash"
  fish_completion "completions/movidesk-cli.fish"
  zsh_completion "completions/movidesk-cli.zsh"

  # No zap stanza required

end
