# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MovideskCli < Formula
  desc "CLI for the Movidesk REST API"
  homepage "https://github.com/jonasandre/movidesk-cli"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jonasandre/movidesk-cli/releases/download/v1.0.0/movidesk-cli_1.0.0_darwin_amd64.tar.gz"
      sha256 "5d128c3acaae4bc6afb99b701ef94102bc29afa37da6f535f0f8242c4b44582a"

      define_method(:install) do
        bin.install "movidesk-cli"
        generate_completions_from_executable(bin/"movidesk-cli", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jonasandre/movidesk-cli/releases/download/v1.0.0/movidesk-cli_1.0.0_darwin_arm64.tar.gz"
      sha256 "964be95e33736f0714f52701f7ff1610c555e4ae6d50c25518e7598b543fcb37"

      define_method(:install) do
        bin.install "movidesk-cli"
        generate_completions_from_executable(bin/"movidesk-cli", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jonasandre/movidesk-cli/releases/download/v1.0.0/movidesk-cli_1.0.0_linux_amd64.tar.gz"
      sha256 "06bf7cbc678c406a1400200ec0a42ec51ae66b9358c2c29b475351f172da0aae"
      define_method(:install) do
        bin.install "movidesk-cli"
        generate_completions_from_executable(bin/"movidesk-cli", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jonasandre/movidesk-cli/releases/download/v1.0.0/movidesk-cli_1.0.0_linux_arm64.tar.gz"
      sha256 "a108e8c2d38458b95c7a4a17802e9c9c7bf99c23363686d71facf578dea6878b"
      define_method(:install) do
        bin.install "movidesk-cli"
        generate_completions_from_executable(bin/"movidesk-cli", "completion")
      end
    end
  end

  test do
    assert_match "movidesk-cli", shell_output("#{bin}/movidesk-cli --version")
  end
end
